version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    volumes:
      # 持久化存储配置数据
      - app-data:/app/.next/cache/local-storage

volumes:
  app-data: 